sudo: false

dist: trusty

language: rust

os:
- linux
- osx

rust:
- nightly
- beta
- stable

addons:
  sources:
    - llvm-toolchain-trusty-3.9 # Provides clang-3.9
  apt:
    packages:
    - binutils-dev
    - clang-3.9               # Required for bindgen
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_install:
- source ./ci/before_install.sh

env:
  matrix:
  - PROFILE="--release"
  - PROFILE=""

script:
- PROFILE="$PROFILE" ./ci/script.sh
