[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "Find the set of shared libraries loaded in the current process with a cross platform API"
documentation = "https://docs.rs/findshlibs"
keywords = ["dyld", "dylib", "shared", "library", "dl_iterate_phdr"]
license = "Apache-2.0/MIT"
name = "findshlibs"
readme = "./README.md"
repository = "https://github.com/gimli-rs/findshlibs"
version = "0.3.3"

[badges.coveralls]
repository = "gimli-rs/findshlibs"

[badges.travis-ci]
repository = "gimli-rs/findshlibs"

[build-dependencies.bindgen]
default-features = false
version = "0.31.3"

[dependencies]
cfg-if = "0.1.2"
lazy_static = "0.2.9"

[features]
nightly = []
